footprint: [[0.5, -0.35], [0.5, 0.35], [-0.5, 0.35], [-0.5, -0.35]] # Wheel
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.5

resolution: 0.05

static:
  map_topic: /map
  subscribe_to_updates: true

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, clearing: true, marking: true, obstacle_range: 2.5, min_obstacle_height: -2.0, max_obstacle_height: 2.0, raytrace_range: 3.0}

inflation_layer:
  inflation_radius: 0.2
