scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilterInPlace
  params:
    lower_angle: -1.8326 #0.261799 #-1.8326 #-3.13
    upper_angle: 0.261799 #1.8326 #0.261799
    # -1.8326  0.261799  
