frequency: 50
sensor_timeout: 0.1

two_d_mode: true
publish_tf: true
publish_acceleration: false
print_diagnostics: false
debug: false

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: /odom
odom0_config: [true, true, false,
               false, false, true,
               false, false, false,
              false, false, true,
              false, false, false]
odom0_differential: true
odom0_relative: false

imu0: /vectornav/IMU
imu0_config: [true, true, false,
              false, false, true,
              false, false, false,
              false, false, true,
              false, false, false]
imu0_differential: false
imu0_relative: true
imu0_remove_gravitational_acceleration: true
